config/routes.rb
Blog::Application.routes.draw do
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/login' => "sessions#new", :as => "login"
  match '/signup' => "users#new", :as => "signup"

  resources :articles
  resources :users
  resources :sessions

  root :to => "articles#index"

end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Slug

  field :title
  field :published_at, :type => Date
  field :articleid, :type => Integer, :default => 1
  field :body

  slug :title
  
end

app/models/user.rb
class User
  include Mongoid::Document

  field :email, :type => String
  field :password_hash, :type => String
  field :password_salt, :type => String

  attr_accessible :email, :password, :password_confirmation
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email, password)
    user = User.where(:email => email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end 
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end    
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user
  helper_method :logged_in?

  private
    
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    # Filter method to enforce a login requirement
    # Apply as before_filter on any controleller you want to protect
    def authenticate
      logged_in? ? true : access_denied
    end
    
    def logged_in?
      current_user.is_a? User
    end

    def access_denied
      redirect_to login_path, :notice => "Please, login to continue"
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :authenticate, :except => [:index, :show]

  # GET /articles
  # GET /articles.xml
  def index
    @articles = Article.all.desc(:published_at)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    #@article = Article.find(params[:id])
    @article = Article.find_by_slug(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new

    if Article.last
      @article.articleid = Article.last.articleid + 1
    else
      @article.articleid = 1
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find_by_slug(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @article = Article.find_by_slug(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = Article.find_by_slug(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create 
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "You have logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "You've logged out."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
  @user = User.new
end

def create
  @user = User.new(params[:user])
  if @user.save
    redirect_to root_url, :notice => "Signed up!"
  else
    render "new"
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<fieldset>
		<ol>
			<li>
				<p>Article #: <%= @article.articleid %></p>
				<%= f.text_field :articleid %>
			</li>
			<li>
				<%= f.label :title %>
				<%= f.text_field :title %>
			</li>
			<li>
				<%= f.label :published_at %>
				<%= f.date_select :published_at %>
			</li>
			<li>
				<%= f.label :body %>
				<%= f.text_area :body %>
			</li>
		</ol>
	</fieldset>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
	<article class="post">
		<div>
			<hgroup>
				<h1><%= link_to article.title, article %></h1>
				<h2>
					<time datetime="2010-05-06" pubdate>
						<div>
							<span><%= article.published_at.strftime("%-d") %></span>
							<span><%= article.published_at.strftime("%B") %></span>
							<span><%= article.published_at.strftime("%Y") %></span>
						</div>
					</time>
				</h2>
			</hgroup>
			<section>
				<%= raw(truncate(article.body, :length => 700, :separator => ' ')) %>
			</section>
		</div>
		<footer>
			<%= link_to 'Read More', article, :class => 'read-more' %>
			<%= link_to 'Tweet', "http://twitter.com/home?status=#{article.title}", :class => 'share' %>
		</footer>
	</article>

  <!-- <%= link_to 'Edit', edit_article_path(article) %>
	<%= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete %> -->
<% end %>

<!-- <%= link_to 'New Article', new_article_path %> -->

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<article class="post">
	<div>
		<hgroup>
			<h1><%= link_to @article.title, @article %></h1>
			<h2>
				<time datetime="2010-05-06" pubdate>
					<div>
						<span><%= @article.published_at.strftime("%d") %></span>
						<span><%= @article.published_at.strftime("%B") %></span>
						<span><%= @article.published_at.strftime("%Y") %></span>
					</div>
				</time>
			</h2>
		</hgroup>
		<section>
			<%= raw(@article.body) %>
		</section>
	</div>
	<% if current_user  %>
		<%= link_to 'Edit', edit_article_path(@article) %> |
		<%= link_to 'Back', articles_path %>
	<% end %>
</article>	

app/views/layouts/application.html.erb
<!doctype html>
<%- # paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -%>
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

	<%- # Always force latest IE rendering engine (even in intranet) & Chrome Frame. Remove this if you use the .htaccess -%>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<title>Blog</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<%- # Mobile viewport optimized: j.mp/bplateviewport -%>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

	<%- # Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -%>
  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">

	<%- # CSS: implied media="all" -%>
  <%= stylesheet_link_tag 'style' %>

	<%- # Uncomment if you are specifically targeting less enabled mobile browsers -%>
	<%#= stylesheet_link_tag 'handheld', :media => 'handheld' %>

	<%= csrf_meta_tag %>

	<%- # All JavaScript at the bottom, except for Modernizr which enables HTML5 elements & feature detects -%>
	<%= javascript_include_tag 'modernizr-1.7.min.js' %>

	<%- # Typekit -%>
	<%= javascript_include_tag 'http://use.typekit.com/ama4orc.js' %>
	<%= javascript_tag 'try{Typekit.load();}catch(e){}' %>
  
</head>

<body>

	<header role="banner">
		<div class="content-wrapper">
			<hgroup>
				<h1><a href="<%= root_url %>">Forebits</a></h1>
				<h2>A blog of Dimitar Haralanov</h2>
			</hgroup>
			<section id="socials">
				<ul>
					<li><%= link_to "Twitter", "http://twitter.com/dalizard" %></li>
					<li><%= link_to "Last.fm", "http://last.fm/user/dalizard" %></li>
					<li><%= link_to "Ember", "http://emberapp.com/dalizard/" %></li>
				</ul>
			</section>
			<nav>
 				<% if current_user %>
					<p>Logged in as <%= current_user.email %>
					<%= link_to 'Logout', logout_path  %>
				<% end %>
			</nav>
		</div>
	</header>
	
	<section role="main">
		<div class="content-wrapper">
			<% flash.each do |name, msg| %>
				<%= content_tag :div, msg, :id => "flash_#{name}" %>
			<% end %>
			<%= yield %>
		</div>
	</section>
	
	<footer role="contentinfo">
			<div class="content-wrapper">
				<p>Copyright &copy; 2011 Dimitar Haralanov</p>
			</div>
	</footer>

	<%- # JavaScript at the bottom for fast page loading -%>

	<%- # Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if necessary -%>
	<%= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.js' %>
	<%= javascript_tag %{!window.jQuery && document.write(unescape('%3Cscript src="/javascripts/jquery-1.5.1.min.js"%3E%3C/script%3E'))} %>

	<%= javascript_include_tag 'rails', 'hoverIntent', 'application', :cache => true %>

	<%- # Fix any <img> or .png_bg bg-images. Also, please read goo.gl/mZiyb -%>
	<!--[if lt IE 7 ]>
		<%= javascript_include_tag 'dd_belatedpng.js' %>
		<%= javascript_tag %{DD_belatedPNG.fix('img, .png_bg')} %>
	<![endif]-->

	<%- # mathiasbynens.be/notes/async-analytics-snippet Change UA-XXXXX-X to be your site's ID -%>
	<!-- <%- if Rails.env.production? -%>
		<script>
		  var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
		  (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
		  g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
		  s.parentNode.insertBefore(g,s)}(document,'script'));
		</script>
	<%- end -%> -->

</body>

</html>

app/views/users/new.html.erb
<div class="content-wrapper">
	<h1>Sign Up</h1>
	<%= form_for @user do |f| %>
		<% if @user.errors.any? %>
			<div class="error-messages">
				<h2>Form is invalid</h2>
				<ul>
					<% for message in @user.errors.full_messages %>
						<li><%= message %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<p>
			<%= f.label :email %>
			<%= f.text_field :email %>
		</p>
		<p>
			<%= f.label :password %>
			<%= f.password_field :password %>
		</p>
		<p>
			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation %>
		</p>
		<p class="button"><%= f.submit %></p>
	<% end %>
</div>